@startuml

package "Host Apps" {
component log [
WLogHostApp
"com.binblob.wasp-launcher.host-app.log"
]

component config [
WConfigHostApp
"com.binblob.wasp-launcher.host-app.config"
]

component debugger [
WGuestAppWebDebugger
"com.binblob.wasp-launcher.host-app.web-debugger"
]

component web_init [
WWebInitHostApp
"com.binblob.wasp-launcher.host-app.web::init"
]

component starter [
WGuestAppStarter
"com.binblob.wasp-launcher.host-app.guest-apps"
]

component model [
WGuestModelLoadApp
"com.binblob.wasp-launcher.host-app.model-load"
]

component template [
WTemplateLoadHostApp
"com.binblob.wasp-launcher.host-app.template-load"
]

component broker [
WBrokerHostApp
"com.binblob.wasp-launcher.host-app.broker"
]

component web_start [
WWebHostApp
"com.binblob.wasp-launcher.host-app.web::start"
]

config .-down-> log
debugger .-down-> config
web_init .-down-> config
starter .-down-> web_init

model .-down-> starter
template .-down-> starter
broker .-down-> starter

web_start .-down-> model
web_start .-down-> template
web_start .-down-> broker

}

@enduml
